swagger: '2.0'
info:
  description: |
    ## Introduction
    API Spec for the legend, naive now.
  version: 0.0.1
  title: The Legend
  contact:
    email: xuylin@sjtu.edu.cn
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2573/7056/collections/cskins_model_icons_no_text_square_black-12_large.png?v=1518446092
securityDefinitions:
  Bearer:
    description: JWT Authentication
    type: apiKey
    name: Authorization
    in: header
host: example.legend.io
basePath: /api/v1
tags:
- name: users
- name: projects
schemes:
- http
- https
paths:
  '/users/login':
    post:
      tags:
      - users
      summary: User login
      description: Input phone number and password to login
      parameters: 
      - name: user
        in: body
        description: Input phone number and password to login
        required: true
        schema:
          required: 
          - phoneNumber
          - password
          properties:
            phoneNumber:
              type: string
            password:
              type: string
      responses:
        201:
          description: Login successfully
          schema:
            properties:
              message:
                description: the returned message
                type: string
              token:
                description: the generated token for the user
                type: string
        401:
          description: Login failed
          schema:
            properties:
              message:
                description: the returned message
                type: string
    
  /:
    get:
      security:
        - Bearer: []
      responses:
        '200':
          description: 'Will send `Authenticated`'
        '403': 
          description: 'You do not have necessary permissions for the resource'